;; Test 26: Register spilling (more than 12 variables)
;; This test has 15 variables, forcing 3 of them to be spilled to the stack
(let ([v1 1])
  (let ([v2 2])
    (let ([v3 3])
      (let ([v4 4])
        (let ([v5 5])
          (let ([v6 6])
            (let ([v7 7])
              (let ([v8 8])
                (let ([v9 9])
                  (let ([v10 10])
                    (let ([v11 11])
                      (let ([v12 12])
                        (let ([v13 13])
                          (let ([v14 14])
                            (let ([v15 15])
                              (+ v1 (+ v2 (+ v3 (+ v4 (+ v5 (+ v6 (+ v7 (+ v8 (+ v9 (+ v10 (+ v11 (+ v12 (+ v13 (+ v14 v15)))))))))))))))))))))))))))))
